### PR TITLE
[24] Add Execution Environment for JavaSE-24

### PR DESCRIPTION
**Pull request by stephan-herrmann**
+ Start the BETA_JAVA24 branch
+ recognize JavaSE-24
+ bump version by +50

Fixes https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/551

### CODE REVIEW

**Comment by stephan-herrmann** [comment]
@jarthana  @noopur2507  any objections against pushing this as the new BETA_JAVA24?

When that's done, what other places must be informed so they could pick it up?
* How can jdt.core PR builds find it? 
* What about Y-Builds?
 I have no clue how those are configured, is any of its configuration in git, actually?

**Comment by stephan-herrmann** [comment]
I guess I found what steers the Y-Build: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/cje-production/streams/repositories_java24.txt

**Comment by stephan-herrmann** [comment]
I made my request for comments a bit more formal :)

**Comment by stephan-herrmann** [comment]
I am a bit reluctant to push this, simply because I never created a new BETA-branch on the public repo :)

If, however, no-one has time and/or advice I will try to push on the weekend. Some follow-up questions may remain even then, though.

**Comment by stephan-herrmann** [comment]
I created https://github.com/eclipse-jdt/eclipse.jdt.debug/tree/BETA_JAVA24 which was then successfully build in https://ci.eclipse.org/jdt/job/eclipse.jdt.debug-github/job/BETA_JAVA24/

To get Y-Builds updated I filed https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2505

**Comment by noopur2507** [comment]
@stephan-herrmann We had Diwali holidays so seeing your comments now. Thanks for taking this up!

**Comment by stephan-herrmann** [comment]
> @stephan-herrmann We had Diwali holidays so seeing your comments now. Thanks for taking this up!

Sure. I hope you had some light to celebrate indeed.

**Comment by stephan-herrmann** [comment]
In hindsight, this change was a bit unfortunate, because I side-stepped the approach of replicating changes from the previous iteration. See that I missed several locations needing to be updated: 
* https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/616
* https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/635

So the last "good" iteration was https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/419

**Pull request closed without merging**
