### PR TITLE
Adding pomless build to JDT debug

### PR DESCRIPTION
**Pull request by vogella**
This enables pomless builds for JDT debugand removes the simple pom files.

Currently this is only one file, but at least the main one which is most frequently changed (jdt.debug).

Future commits can reduce the usage of pom files further. This might require enhancements in pomless builds to specify the test classes and suites https://github.com/eclipse-tycho/tycho/discussions/3105

## Author checklist

- [ ] I have thoroughly tested my changes
- [ ] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [ ] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by vogella** [comment]
cc @jukzi 


Btw. this repo is tiny. Why not merge it with UI so that the releng work is further reduced? Like we did in platform and PDE

**Comment by jukzi** [comment]
> Btw. this repo is tiny. Why not merge it with UI so that the releng work is further reduced? Like we did in platform and PDE

Afaik there are different people that care about.

**Review by jukzi — APPROVED** [review]

**Comment by vogella** [comment]
> > Btw. this repo is tiny. Why not merge it with UI so that the releng work is further reduced? Like we did in platform and PDE
> 
> Afaik there are different people that care about.

I don't understand this statement. Are you saying that other people work these repos? If that is what you are saying I fail to understand why this would prevent releng simplification. JDT guys have the same commit rightrs for debug / ui and core and if they don't want to see the other plug-ins they could just not import them.

But no need to get into a heavy discussion here, I do not care enough, if JDT does not want to merge, fine for me just wanted to bring up the idea.

**Comment by akurtakov** [comment]
https://github.com/eclipse-jdt/eclipse.jdt.debug/blob/master/org.eclipse.jdt.debug/pom.xml seems to be up for removal too .

**Comment by vogella** [comment]
> https://github.com/eclipse-jdt/eclipse.jdt.debug/blob/master/org.eclipse.jdt.debug/pom.xml seems to be up for removal too .

I think that is the one I removed, see https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/352/files

**Review by akurtakov — APPROVED** [review]

**Comment by akurtakov** [comment]
My bad, I mixed things again.

**Pull request merged**
