### PR TITLE
update Require-Bundle to org.eclipse.jdt.core 3.40

### PR DESCRIPTION
**Pull request by jukzi**
needed since beta 23 merge

### CODE REVIEW

**Comment by jukzi** [comment]
`Missing requirement: org.eclipse.jdt.debug 3.21.600.qualifier requires 'osgi.bundle; org.eclipse.jdt.core [3.40.0,4.0.0)' but it could not be found: See log for details` 
WHY?

**Comment by akurtakov** [comment]
Due to https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2358 builds are unstable (as can be seen at https://download.eclipse.org/eclipse/downloads/index.html) and thus are not promoted to I-builds composite repo.

**Comment by iloveeclipse** [comment]
> `it could not be found: See log for details`
> WHY

Because since beta 23 branch merge we didnt had a stable SDK build.

See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2358

**Comment by jukzi** [comment]
ignoring unrelated ObjectReferenceTest.testJDIEntryCount

**Pull request merged**
