### PR TITLE
Fix I-Build test failures of VMInstallTests

### PR DESCRIPTION
**Pull request by HannesWell**
## What it does

- Handle assumption violations in VMInstallTests the JUnit-3 way
- Disable error-testing for VMs of the latest supported version (which cannot not fail).

Fixes the problem in https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/175#issuecomment-2089713868

## How to test

Run the `VMInstallTests` with a Java-22 EE respectively a corresponding JVM and run the tests with the `NON_MODULAR_JAVA_HOME` environment variable pointing to a proper VM install respectivly without that while making sure that there is no co-located VM installation found.

## Author checklist

- [x] I have thoroughly tested my changes
- [x] The change is following the [coding conventions](https://wiki.eclipse.org/Platform/How_to_Contribute#Coding_Conventions)
- [x] I have signed the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)

### CODE REVIEW

**Comment by HannesWell** [comment]
@iloveeclipse could you please have a look at this?

**Comment by iloveeclipse** [comment]
Looks OK in the IDE, let see what happens within SDK build.

**Comment by iloveeclipse** [comment]
> Looks OK in the IDE, let see what happens within SDK build.

It fails already on jenkins with

```
junit.framework.AssertionFailedError: No tests found in org.eclipse.jdt.debug.tests.core.VMInstallTests
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.TestCase.fail(TestCase.java:223)
```

**Comment by HannesWell** [comment]
> > Looks OK in the IDE, let see what happens within SDK build.
> 
> It fails already on jenkins with
> 
> ```
> junit.framework.AssertionFailedError: No tests found in org.eclipse.jdt.debug.tests.core.VMInstallTests
> 	at junit.framework.Assert.fail(Assert.java:57)
> 	at junit.framework.TestCase.fail(TestCase.java:223)
> ```

This really is not simple. The `AutomatedSuite`, which calls the `VMInstallTests` seems to be a pure JUnit-3 suite, which cannot handle Junit-4 cases. Consequently the `AutomatedSuite` would have to be migrated too (or first).
I have no chosen the simpler way to just catch the `org.junit.AssumptionViolatedException` thrown if the assumption is violated. Now the test just passes instead of being marked as skipped, but it at least does not fail. 
I added a TODO, so that the somebody in the future hopefully removes that if those tests will be JUnit-4 or later tests one day.

**Comment by iloveeclipse** [comment]
Test failure unrelated.

**Pull request merged**
