### PR TITLE
Avoid reusing of not thread-safe SimpleDateFormat

### PR DESCRIPTION
**Pull request by jukzi**
SimpleDateFormat.format(new Date());
returns same string as immutable and thread-safe
  DateTimeFormatter.format(new Date().toInstant())

### CODE REVIEW

**Review by mpalat — APPROVED** [review]
+1
Please submit after all the tests are green
Thanks @jukzi

**Comment by jukzi** [comment]
@mpalat there is only an unrelated random fail

org.eclipse.jdt.debug.tests.ui.DebugHoverTests.testBug572629_ChainFieldHover_ArrayLengthChainsOnVariableThisExpression_ExpectValueFromChain

i dont't know how to get that green other then a rebuild (which i can not trigger)and hope for randomness disappear

**Comment by iloveeclipse** [comment]
I've triggered rebuild, will see.

**Comment by jukzi** [comment]
@iloveeclipse thanks. it's gone

**Pull request merged**
