### PR TITLE
Use ASM 9.4

### PR DESCRIPTION
**Pull request by iloveeclipse**
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/606

TODO:
See https://github.com/eclipse-jdt/eclipse.jdt.debug/tree/master/org.eclipse.jdt.launching.javaagent#readme

### CODE REVIEW

**Comment by akurtakov** [comment]
Should this one be targetted for M3?

**Comment by iloveeclipse** [comment]
> Should this one be targetted for M3?

Ideally yes, see the list what need to be done: https://github.com/eclipse-jdt/eclipse.jdt.debug/tree/master/org.eclipse.jdt.launching.javaagent#readme

I will check if that is easy & trivial in a moment, just haven't had time yet, due various meetings :-)

**Comment by iloveeclipse** [comment]
Note: it looks like a "final" change requires a "final" ASM support for Java 20, which is not yet there (`Opcodes.V19` is the latest one version supported by ASM I see in the IDE, even if release notes claim : 
https://mail.ow2.org/wws/arc/asm/2022-10/msg00000.html
```
Release notes:
- new Opcodes.V20 constant for Java 20).
```

Either org.objectweb.asm_9.4.0.v20221013-0857.jar we get from Orbit isn't the 9.4 version, or 9.4 doesn't have `Opcodes.V20`.

???

**Comment by iloveeclipse** [comment]
> Either org.objectweb.asm_9.4.0.v20221013-0857.jar we get from Orbit isn't the 9.4 version, or 9.4 doesn't have `Opcodes.V20`.

I see **no** `Opcodes.V20` in the ASM 9.4 version from Orbit (org.objectweb.asm_9.4.0.v20221013-0857.jar), but I do see   `Opcodes.V20` version in the ASM we get from maven. O-o.

**Comment by akurtakov** [comment]
Yet another reason to not use Orbit. https://git.eclipse.org/c/orbit/orbit-recipes.git/tree/asm/org.objectweb.asm_9.4.0/pom.xml#n18 is the issue.

**Comment by akurtakov** [comment]
make sure that you have the upstream version , not Orbit and it will be fine.

**Comment by iloveeclipse** [comment]
see https://git.eclipse.org/r/c/orbit/orbit-recipes/+/196626

I will update this PR later

**Pull request merged**
