### PR TITLE
try to get OpenFromClipboardTests.testMethod_11 stable

### PR DESCRIPTION
**Pull request by jukzi**
* use concurrent data structure for inter-thread communication
* fix wait for charsetsjobs instead of exclude for waiting for them
* use monotonic nantotime

### CODE REVIEW

**Comment by jukzi** [comment]
https://ci.eclipse.org/jdt/job/eclipse.jdt.debug-github/job/PR-446/7/consoleText is spammed with 15969 logs regarding "VeryLongClasspathWithClasspathOnlyJar" which was not the case in on master (https://ci.eclipse.org/jdt/job/eclipse.jdt.debug-Github/job/master/89/consoleText) :-(

```
[2024-06-07T07:00:30.939Z] !MESSAGE Failed to retrieve children for lib/library0.jar (not open) [in test ä VeryLongClasspathWithClasspathOnlyJar]
[2024-06-07T07:00:30.939Z] !STACK 1
[2024-06-07T07:00:30.939Z] Java Model Exception: Error in Java Model (code 969): test ä VeryLongClasspathWithClasspathOnlyJar does not exist
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:572)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:233)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:507)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:227)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:585)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:308)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:294)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.core.JavaElement.getChildren(JavaElement.java:249)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.core.SearchableEnvironment.hasSubPackageInUnnamedModule(SearchableEnvironment.java:1306)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.core.SearchableEnvironment.getModulesDeclaringPackage(SearchableEnvironment.java:1054)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.compiler.env.IModuleAwareNameEnvironment.getUniqueModulesDeclaringPackage(IModuleAwareNameEnvironment.java:113)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.compiler.lookup.ModuleBinding$UnNamedModule.getDeclaredPackage(ModuleBinding.java:102)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createPlainPackage(LookupEnvironment.java:1118)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.buildTypeBindings(CompilationUnitScope.java:138)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.buildTypeBindings(LookupEnvironment.java:515)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.compiler.Compiler.internalBeginToCompile(Compiler.java:855)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.compiler.Compiler.beginToCompile(Compiler.java:393)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.compiler.Compiler.resolve(Compiler.java:1037)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.compiler.Compiler.resolve(Compiler.java:1110)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:280)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:346)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:186)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:92)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:740)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:805)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1311)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:132)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy$1.run(JavaReconcilingStrategy.java:94)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:91)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.initialReconcile(JavaReconcilingStrategy.java:189)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.ui.text.CompositeReconcilingStrategy.initialReconcile(CompositeReconcilingStrategy.java:125)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.initialReconcile(JavaCompositeReconcilingStrategy.java:139)
[2024-06-07T07:00:30.939Z] 	at org.eclipse.jface.text.reconciler.MonoReconciler.initialProcess(MonoReconciler.java:100)
[2024-06-07T07:00:30.940Z] 	at org.eclipse.jdt.internal.ui.text.JavaReconciler.initialProcess(JavaReconciler.java:421)
[2024-06-07T07:00:30.940Z] 	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:177)
[2024-06-07T07:00:30.940Z] !SUBENTRY 1 org.eclipse.jdt.core 4 969 2024-06-07 07:00:30.693

```

**Comment by akurtakov** [comment]
What is the status of this one?

**Comment by jukzi** [comment]
> What is the status of this one?

its still draft as i did not find the time to get it right.

**Comment by jukzi** [comment]
> Is there hope for this one?

Thanks for the reminder. ill try to get a look again.

**Pull request closed without merging**
