### PR TITLE
DetectVMInstallationsJob: defer detection until needed.

### PR DESCRIPTION
**Pull request by jukzi**
So that it does not run in jdt.core tests at all

https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1190

### CODE REVIEW

**Comment by jukzi** [comment]
for me it fixes locally running org.eclipse.jdt.core.tests.model.JavaSearchBugsTests.testBug178847()

**Comment by jukzi** [comment]
@mickaelistria please review if that still fulfills the original intend of DetectVMInstallationsJob

**Comment by jjohnstn** [comment]
@jukzi FYI @mickaelistria is on vacation until after Tuesday.

**Comment by jukzi** [comment]
@jjohnstn can you review? You did participate in the initial commit.

**Comment by jjohnstn** [comment]
@jukzi I'll give it a look.  Any idea about the test failures?  Do you need to rebase?

**Comment by jukzi** [comment]
> Any idea about the test failures?

those are only random. i just rebased and had no errors before. See https://ci.eclipse.org/jdt/job/eclipse.jdt.debug-github/job/PR-293/1/

**Comment by jjohnstn** [comment]
Hi @jukzi I tried running the tests locally and they run fine.  I ran into a problem until I switched from using the JustJ JRE to a Java 17 JDK I had.  Is is possible that the JDI tests are finding a bogus VM that has been created by other tests and then it is being discovered?  I am fine with the patch and will approve, but you might want to try disabling the detection when running the JDI tests to see if that fixes the problem.  I have to leave and won't be back in time for the deadline.

**Review by jjohnstn — APPROVED** [review]
Looks good.

**Comment by jukzi** [comment]
> I switched from using the JustJ JRE to a Java 17 JDK I had

That sounds like a local error only - which we could fix in future.

**Pull request merged**
